CREATE DATABASE schoolapp;
USE schoolapp;

CREATE TABLE TEACHERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(45) NOT NULL,
    LASTNAME VARCHAR(45) NOT NULL
);

CREATE TABLE STUDENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(45) NOT NULL,
    LASTNAME VARCHAR(45) NOT NULL
);

CREATE TABLE TEACHERS_STUDENTS (
    TEACHER_ID INT,
    STUDENT_ID INT,
    PRIMARY KEY (TEACHER_ID, STUDENT_ID),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID)
);

CREATE USER 'schoolapp'@'localhost' IDENTIFIED BY 'schoolapp12345';
GRANT ALL PRIVILEGES ON schoolapp.* TO 'schoolapp'@'localhost';
FLUSH PRIVILEGES;
